### PR TITLE
Fix variable lookup during requirements analysis

### LINKED ISSUE #1914: Local variables pick up requirements of global vars with the same name
**Describe the bug**
Requirements analysis is apparently deciding that locally-bound variable (e.g. the argument of a lambda) have the same requirements as globally-defined things with the same name.

**To Reproduce**
```
> def m = move end
> requirements \m. m
```
Note that the reported requirements includes `treads`, which are definitely required to execute `move` but should not be required for the identity function `\m .m`.

**Additional context**
This must have been introduced by the refactoring in #1906 (which I really should have tested more thoroughly!).

### PR DESCRIPTION
**Pull request by byorgey**
When I refactored requirements analysis during #1906 I didn't properly update the variable case: the code continued to look up the variable in `ctx` which used to be the name of the local context being passed around; after the refactoring, however, `ctx` was the name of the initial context passed to the top-level `requirements` function, and the local context was passed around as a `Reader` effect.  Thus, the lambda case (for example) was correctly deleting the bound variable from the context, but then when checking the variable inside the body of the lambda we looked up its requirements in the initial, global context instead of the modified local one.

This PR fixes the issue and also adds some test cases, one of which was failing before this fix.

Fixes #1914.

### CODE REVIEW

File: test/unit/TestRequirements.hs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+checkRequirements code expect = check code (expect . view processedRequirements)
+
+requiresCap :: Text -> Capability -> Assertion
+requiresCap code cap = checkRequirements code ((cap `S.member`) . capReqs)
+
+check :: Text -> (ProcessedTerm -> Bool) -> Assertion
+check code expect = case processTerm code of
+  Left err -> assertFailure $ "Term processing failed: " ++ from @Text err
+  Right Nothing -> assertFailure "Term is empty"
+  Right (Just pt) -> assertBool "Predicate was false!" (expect pt)
```
Comment (xsebek) [inline test/unit/TestRequirements.hs:55]: Is this not used anywhere else? I would expect this to be in `TestUtil`.

**Review by xsebek — APPROVED** [review]
Nice unit tests! 👍

File: test/unit/TestRequirements.hs (hunk 1 above)
Comment (byorgey) [reply test/unit/TestRequirements.hs]: Good idea, I'll move it there.
