### PR TITLE
Fix lambda precedence

### LINKED ISSUE #1468: Parameters to case are not formatted with parens
**Describe the bug**

I noticed in #1459, that the case command parameters are formatted wrong.

They are both of type `a -> cmd b`, but are formatted without parentheses.

**To Reproduce**

Try to format the `hanoi-invariant.sw`:
```
❯ cabal run swarm -O0 -- format scenarios/Challenges/_hanoi/hanoi-invariant.sw
```

In the original, there are cases like this:
```
case mn (\_. //...
```
but in the formatted version, the parens are dropped:
```
case mn \_. wait 16; /* ... */ \_. return ()
```

**Expected behavior**

The precedence should force the bind chains in parentheses.

### PR DESCRIPTION
**Pull request by xsebek**
- give lambdas lower precedence (9) then application (10)
- closes #1468

Before (with #1459):
```
❯ cabal run swarm -O0 -- format <(echo '\\m. case m (\\x. x + 1) (\\y. y * 2)')
\m. case m \x. x + 1 \y. y * 2
```

After:
```
❯ cabal run swarm -O0 -- format <(echo '\\m. case m (\\x. x + 1) (\\y. y * 2)')
\m. case m (\x. x + 1) (\y. y * 2)
```

### CODE REVIEW

File: src/Swarm/Language/Pretty.hs [hunk 1]
```diff
@@ -188,7 +188,9 @@ instance PrettyPrec Term where
   prettyPrec _ (TVar s) = pretty s
   prettyPrec _ (TDelay _ t) = group . encloseWithIndent 2 lbrace rbrace $ ppr t
   prettyPrec _ t@TPair {} = prettyTuple t
-  prettyPrec _ t@(TLam {}) = prettyLambdas t
+  prettyPrec p t@(TLam {}) =
+    pparens (p > 9) $
+      prettyLambdas t
```
Comment (xsebek) [inline src/Swarm/Language/Pretty.hs:193]: @byorgey I assume this is overly pessimistic - in the example case, only the inner lambda requires parentheses.

However, the least amount of parentheses might be harder to read. 😄

Comment (byorgey) [reply src/Swarm/Language/Pretty.hs:193]: Hah, yes, in theory, a lambda at the very tail end of an expression does not need parentheses, but that would be annoying to read.  I think this is fine.

**Review by byorgey — APPROVED** [review]
