### PR TITLE
Remove superfluous trobotContext lens

### LINKED ISSUE #394: Inner build does not correctly require Drill
From #373 by @byorgey:

> So I ran into one additional issue while testing out some things. In creative mode I tried something like this:
> ```
> def forever = \c. c ; forever c end
> def unblock = try {drill forward} {} end
> def push = unblock; move end
> 
> build {forever (push; build {turn right; forever push})}
> ```
> ...
> However, it doesn't work. The initial robot works fine, drilling along and building another robot at each step. However, all those secondary robots don't end up with a drill device and crash with a fatal error when they try to execute the drill command.

The problem was present before, but not visible until the robots stopped without a drill.

In this new iron age, it is immediately a fatal bug once the robot attempts to drill.

## Screenshots

A bronze age screenshot from the main branch:

Screenshot from 2022-06-14 17-01-12
<sup>It's almost the same now too, so I won't include another screenshot here.</sup>

Log of the robot missing a drill:

Screenshot from 2022-06-14 17-19-14

## Additional context

I traced the issue to the `requiredCaps` function which did not require `CDrill`.

### PR DESCRIPTION
**Pull request by kostmo**
# Motivation

Want to remove dependence of `TRobot` on the `RobotContext` record.  However, a lens `trobotContext` had been added in #817 to fix #394.

# Test

    scripts/run-tests.sh --test-arguments '--pattern "394-build-drill"'

### CODE REVIEW

File: src/swarm-engine/Swarm/Game/Step/Const.hs [hunk 1]
```diff
@@ -1061,7 +1061,7 @@ execConst runChildProg c vs s k = do
         -- Construct the new robot and add it to the world.
         parentCtx <- use robotContext
         newRobot <-
-          zoomRobots . addTRobot (In cmd e s [FExec]) . (trobotContext .~ parentCtx) $
+          zoomRobots . fmap (robotContext .~ parentCtx) . addTRobot (In cmd e s [FExec]) $
```
Comment (byorgey) [inline src/swarm-engine/Swarm/Game/Step/Const.hs:1064]: I think the reason this doesn't work is that it only modifies the `robotContext` of the `Robot` value returned by `addTRobot`, but it does not modify the original `Robot` value which `addTRobot` actually adds to the robot map (of which it then returns a copy).

Comment (byorgey) [reply src/swarm-engine/Swarm/Game/Step/Const.hs:1064]: Maybe we could just have `addTRobot` take a `Maybe RobotContext` as an extra argument?  I don't know if that's actually a good idea, just random brainstorming...

**Review by byorgey — APPROVED** [review]
Ah, wonderful.  I like how this uncovers the fact that the only time we really needed the returned `Robot` was when we were actually setting the context, so now in the common case we can have `addTRobot` return `()` and get rid of a bunch of calls to `void`.
