### PR TITLE
Reset `lastFrameTime` when starting a new scenario

### LINKED ISSUE #853: Newly initialized game tries to "catch up" after sitting in the menu for a while
**Describe the bug**
After spending a while letting the game sit in the menu, when starting a new scenario the game runs really fast for a little bit, as if it thinks it should have been running while the menu was active and it is now trying to "catch up".

**To Reproduce**
I first noticed this when testing out #835 (it was very noticeable since the sheep ran around really fast and quickly drowned themselves) but it can be seen in any scenario where the base has a `clock` installed.
- Start the app
- Let it sit in the menu for a while (e.g. a few minutes)
- Now start the Classic game and look at the clock in the upper right.  It will run fast for a little while and then at some point start running normally.

**Expected behavior**
The game should run at a normal speed regardless of how long you have spent in the menu.

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #853.

### CODE REVIEW

File: src/Swarm/TUI/Model.hs [hunk 1]
```diff
@@ -1053,3 +1054,4 @@ scenarioToUIState siPair u =
       & uiREPL .~ initREPLState (u ^. uiREPL . replHistory)
       & uiREPL . replHistory %~ restartREPLHistory
       & scenarioRef ?~ siPair
+      & lastFrameTime .~ curTime
```
Comment (xsebek) [inline src/Swarm/TUI/Model.hs:1057]: This makes me think we should have something like a `UIGameState` that is reset on a new game. :thinking: 

It should not be possible to carry over things between games both in `GameState` and in `UIState`.

**Review by xsebek — APPROVED** [review]
:+1:

File: src/Swarm/TUI/Model.hs (hunk 1 above)
Comment (byorgey) [reply src/Swarm/TUI/Model.hs:1057]: Or perhaps it means `lastFrameTime` really ought to live in `GameState` (once we fix #516 and #689).
