### PR TITLE
Explicit term-level type argument to `read` command

### LINKED ISSUE #2223: Handle `read` at user-defined types
Currently, the `read` command (#2224) does not work with user-defined types.  It used to simply fail; then for a while it completely crashed the entire game; now after merging #2431 it always succeeds, even when it should not, allowing us to exploit the type system:
```
> read "3" : Bool -- this throws an exception, as it should
read: Could not read "3" at type Bool
> tydef Foo = Bool end
> read "3" : Foo   -- this should not succeed, but it does
it0 : Foo = 3
> if (read "3" : Foo) {} {}
Fatal error: Bad application of execConst ...
```
Fundamentally, the problem is that at runtime we no longer have easy access to tydefs that are in scope, so when we encounter a user-defined type like `Num` we don't know what it should expand to.  There are two ways we could potentially solve this: (1) we could keep track of in-scope tydefs at runtime (maybe we already do this somewhere? I forget, but even if so it would still need to be plumbed through to where we execute `read`), or (2) we could expand away any user-defined types in the type of `read` prior to runtime, *e.g.* at typechecking or elaboration time.  However, in that case we have to be careful to use the correct tydefs that are actually in scope.

### PR DESCRIPTION
**Pull request by byorgey**
- Add `@` syntax for writing types as terms.
- Add a type of types, `Type`.
- Give the `read` command the type `Type -> Text -> a`, and a special typechecking rule such that the type argument (which must be a type literal) becomes the output type.  In other words it really should have a dependent type like `(tau : Type) -> Text -> tau` but I'm not about to add actual dependent types to Swarm. :smile:
- Eagerly expand any user-defined types in an argument to `read`.  Fixes #2223.
- Add some tests.

### CODE REVIEW

File: test/unit/TestLanguagePipeline.hs [hunk 1]
```diff
@@ -744,7 +744,16 @@ testLanguagePipeline =
...
-                "3:15:\n  |\n3 |  def z = 3 end\n  |               ^\nunexpected end of input\nexpecting \"!=\", \"&&\", \"()\", \"++\", \"<=\", \"==\", \">=\", \"def\", \"false\", \"let\", \"require\", \"requirements\", \"stock\", \"true\", \"tydef\", \"||\", '\"', '$', '(', '*', '+', '-', '.', '/', ':', ';', '<', '>', '[', '\\', '^', 'end' keyword for definition of 'x', '{', built-in user function, direction constant, integer literal, or variable name\n"
+                "3:15:\n  |\n3 |  def z = 3 end\n  |               ^\nunexpected end of input\nexpecting \"!=\", \"&&\", \"()\", \"++\", \"<=\", \"==\", \">=\", \"def\", \"false\", \"let\", \"require\", \"requirements\", \"stock\", \"true\", \"tydef\", \"||\", '\"', '$', '(', '*', '+', '-', '.', '/', ':', ';', '<', '>', '@', '[', '\\', '^', 'end' keyword for definition of 'x', '{', built-in user function, direction constant, integer literal, or variable name\n"
+            )
+        ]
+    , testGroup
+        "Typechecking for read #2461"
+        [ testCase
+            "read type argument propagates"
+            ( process
+                "(read @Int \"3\") 4"
```
Comment (xsebek) [inline test/unit/TestLanguagePipeline.hs:752]: Could we have one test that shows what happens when you store a `Type` in a variable and use that as first argument?

File: data/scenarios/Challenges/_flower-count/judge.sw [hunk 2]
```diff
@@ -19,7 +19,7 @@ def judgeCount : Int -> Cmd Unit = \actual.
     (\_. pure ())
     (\p.
       try {
-        let c = (read p : Int) in
+        let c = read @Int p in
         if (c == actual) { win } {}
```
Comment (xsebek) [inline data/scenarios/Challenges/_flower-count/judge.sw:23]: I suppose we can't auto convert it, because the type might not have been specified? 🤔

File: src/swarm-lang/Swarm/Language/Parser/Term.hs [hunk 3]
```diff
@@ -107,6 +107,7 @@ parseTermAtom2 =
           <*> pure Nothing
           <*> (optional (symbol ";") *> (parseTerm <|> (eof $> sNoop)))
         <|> SRcd <$> brackets (parseRecord (optional (symbol "=" *> parseTerm)))
+        <|> TType <$> (symbol "@" *> parseTypeAtom)
```
Comment (xsebek) [inline src/swarm-lang/Swarm/Language/Parser/Term.hs:110]: 🤩

**Review by xsebek — APPROVED** [review]

File: data/scenarios/Challenges/_flower-count/judge.sw (hunk 2 above)
Comment (byorgey) [reply data/scenarios/Challenges/_flower-count/judge.sw:23]: I mean, technically, we could go through and look for syntax specifically of the form `read <expr> : <type>` and convert it to `read <type> <expr>`.  But you're right that might not catch all uses, since the type might have just been inferred.  However, the bigger reason I don't think it's worth trying to do auto-conversion is that `read` itself was added since the 0.6 release.  So someone upgrading directly from 0.6 to 0.7 would have no existing uses of `read` to convert.

File: src/swarm-lang/Swarm/Language/Parser/Term.hs (hunk 3 above)
Comment (byorgey) [reply src/swarm-lang/Swarm/Language/Parser/Term.hs:110]: Yeah, doing it this more general way turned out to be way nicer than making `read` a special syntax form.  It actually wasn't even that hard since we already had types-as-values for the implementation of `read`.

File: test/unit/TestLanguagePipeline.hs (hunk 1 above)
Comment (byorgey) [reply test/unit/TestLanguagePipeline.hs:752]: Oh, drat.  That's a really good suggestion, and it reveals a problem.  The typechecking for `read` only works when it has a literal type argument.  Without full-blown dependent types, we can't typecheck uses of `read` where its output type depends on a *value* passed in at runtime.  With this PR as it stands, you *can* write
```
def T : Type = @Int end; read T "3"
```
and it works --- except that the type inferred for `read T "3"` is `forall a. a`, because the special case in the typechecker for `read` applied to a literal type argument is not triggered.  Of course you can use this to crash the CESK machine, e.g.
```
def T : Type = @Int end; (read T "3") 4
```
I suppose the solution is to add a check in the typechecker to *ensure* that the first argument to `read` is a literal type and not any other kind of expression (with a suitably apologetic error message).

Comment (byorgey) [reply test/unit/TestLanguagePipeline.hs:752]: Fixed by making it an error to give anything other than a type literal as the first argument to `read`.

So technically, right now, you can define variables storing types, like `def mytype : Type = @(Int * Bool) end`, but there's nothing you can do with them!
