### PR TITLE
Fix Semigroup EntityMap instance to update Capabilities map properly when there are overridden devices

### LINKED ISSUE #2240: Overridden standard entities are still suggested as a means to provide a missing capability
**Describe the bug**
If a standard entity has been overridden by a custom entity with the same name, the standard entity will still be suggested if it could provide a missing capability, even if the custom entity does not provide that capability.

**To Reproduce**

Once #2241 is merged, load this scenario:

```
version: 1
name: Overridden entity capabilities
description: |
  Overridden standard entity should not still be suggested for its
  capabilities. The error message should suggest "- tank treads", not
  "- treads or tank treads".
creative: false
entities:
  - name: treads
    display:
      char: '#'
      attr: red
    description:
      - Broken treads
    properties: [known, pickable]
robots:
  - name: base
    dir: east
    devices:
      - logger
      - treads
solution: |
  move
world:
  dsl: |
    {grass}
  palette:
    'B': [grass, null, base]
  upperleft: [0, 0]
  map: |
    B
```

Then try to execute `move`.  The following error message is displayed:
```
You do not have the device required for:
  'move'
  Please equip:
  - treads or tank treads
```
Note that it is correct that we get an error message: even though `treads` are equipped, it is a custom entity that does not provide the `move` capability.  The problem is that `treads` are still suggested in the error message.

**Expected behavior**
The error message should mention only `tank treads` as a possibility for providing the `move` capability.

**Additional context**
Note that this depends on fixing #2239 first, i.e. #2241.

I believe the problem lies in the `Semigroup` instance for `EntityMap`.  If any entities are overridden, they must be appropriately removed from the map in the `entitiesByCap` field.

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #2240.  Fixes the `Semigroup EntityMap` instance so that devices which are overridden are removed from the lists of devices providing certain capabilities.

- Also adds a test scenario which generated an incorrect error message before this fix.
- Also adds the test scenario from #2241 to the test suite which was missed previously.

### CODE REVIEW

File: src/swarm-scenario/Swarm/Game/Entity.hs [hunk 1]
```diff
@@ -429,16 +430,36 @@ data EntityMap = EntityMap
...
+        -- traverseMaybeWithKey allows us in one operation to filter
+        -- the NonEmpty list of devices for each capability, turn the
+        -- resulting lists into Maybe NonEmpty, and then remove from
+        -- the map any that became Nothing.  However, it is more
+        -- general than we need: it gives us access to the key which
+        -- we don't need (this explains the call to 'const'), and runs
+        -- in an arbitrary Applicative which we also don't need (this
+        -- explains the Identity).
+        . M.traverseMaybeWithKey
+          (const (Identity . NE.nonEmpty . NE.filter (notOverridden . device)))
```
Comment (kostmo) [inline src/swarm-scenario/Swarm/Game/Entity.hs:461]: Instead of placing this verbose explanation inline here, shall we expose a simplified version of `traverseMaybeWithKey` in a util class?  Perhaps call the function `filterMaybes`?

**Review by kostmo — APPROVED** [review]

File: src/swarm-scenario/Swarm/Game/Entity.hs (hunk 1 above)
Comment (byorgey) [reply src/swarm-scenario/Swarm/Game/Entity.hs:461]: That's a good idea, I'll do that.

Comment (byorgey) [reply src/swarm-scenario/Swarm/Game/Entity.hs:461]: Oh! It turns out it already exists in `Data.Map`, it's called `mapMaybeWithKey`.  Don't know why I didn't find that one before.
