### PR TITLE
also run `handleInfoPanelEvent` for dialogs other than `GoalModal`

### LINKED ISSUE #1068: Dialogs other than goals dialog do not scroll
**Describe the bug**
Dialogs such as the Commands or Recipes dialogs have a scroll bar displayed, but cannot be scrolled.

**To Reproduce**
1. Start a new Classic game.
2. Press F4 to view the Commands dialog (make sure it does not fit in the window so a scrollbar is displayed).
3. Try to scroll.

**Additional context**
I expect this has been caused by something related to #927, but I am not sure yet.

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #1068.

### CODE REVIEW

**Review by kostmo — APPROVED** [review]
UI programming is a fraught exercise 😵‍💫

File: src/Swarm/TUI/Controller.hs [hunk 1]
```diff
@@ -419,7 +419,7 @@ handleModalEvent = \case
                 uiState . uiGoal . listWidget .= newList
               GoalSummary -> handleInfoPanelEvent modalScroll (VtyEvent ev)
             _ -> handleInfoPanelEvent modalScroll (VtyEvent ev)
-      _ -> return ()
+      _ -> handleInfoPanelEvent modalScroll (VtyEvent ev)
```
Comment (xsebek) [inline src/Swarm/TUI/Controller.hs:422]: I almost wish we returned `EventM Name AppState Bool` to indicate whether the event was handled or fell through.

Then the top handler would know to call the next handler that might be interested.

**Review by xsebek — APPROVED** [review]
