### PR TITLE
Make function chains pretty

### LINKED ISSUE #1473: Optionally break up long types on `->` when pretty-printing
**Describe the bug**
This example code:
```
def harvestbox : dir -> (cmd unit -> cmd unit) -> (cmd unit -> cmd unit) -> cmd unit = \d. \rep1. \rep2.
  doboxP harvest d rep1 rep2 notempty
end
```
is currently pretty-printed as
```
def harvestbox : dir -> (cmd unit -> cmd unit) -> (
    cmd unit -> cmd unit
  ) -> cmd unit = \d. \rep1. \rep2.
  doboxP harvest d rep1 rep2 notempty
end;
```
which looks weird.  I would expect/desire something more like the following, perhaps:
```
def harvestbox : 
  dir ->
  (cmd unit -> cmd unit) ->
  (cmd unit -> cmd unit) ->
  cmd unit
  = \d. \rep1. \rep2.
  doboxP harvest d rep1 rep2 notempty
end;
```
I think the issue is that right now, the only option the pretty-printer has for spreading long function types across multiple lines is to split out parenthesized parts.  But I think we instead need to pretty-print function types in such a way that the pretty-printer knows the right way to optionally break lines at `->`, which I think would mean that parenthesized types are rarely split across multiple lines like that.  But I could imagine it still being the right thing to do in a case like
```
def foo : 
  lots ->
  of ->
  parameters ->
  (
    a ->
    very ->
    long ->
    function ->
    parameter
  ) ->
  more ->
  result
```
So I don't think there's anything wrong with the way we handle parenthesized types per se.

### PR DESCRIPTION
**Pull request by xsebek**
- closes #1473

### CODE REVIEW

File: src/Swarm/Language/Pretty.hs [hunk 1]
```diff
@@ -121,14 +121,27 @@ data Wildcard = Wildcard
...
   prettyPrec _ _ = "_"
 
+-- | Split a function type chain, so that we can pretty print
+--   the type parameters aligned on each line when they don't fit.
+class UnchainableFun t where
+  unchainFun :: t -> [t]
+
+instance UnchainableFun Type where
+  unchainFun (a :->: ty) = a : unchainFun ty
+  unchainFun ty = [ty]
```
Comment (xsebek) [inline src/Swarm/Language/Pretty.hs:131]: @byorgey almost there, just have to figure out why it got too unchained 😅 
```
❯ cabal run swarm -O0 -- format --width 20 example.sw
def harvestbox:
  dir ->
  cmd unit ->
  cmd unit ->
  cmd unit ->
  cmd unit ->
  cmd unit 
  = \d. \rep1. \rep2.
  doboxP harvest d rep1 rep2 notempty
end
```

Comment (byorgey) [reply src/Swarm/Language/Pretty.hs:131]: Haha, oops!  That's odd.  The `UnchainableFun` instance above looks fine to me...

Hmm, maybe we should break up chains of function applications too...
```
def harvestbox
  = \d. \rep1. \rep2.
  doboxP 
    harvest 
    d 
    rep1
    rep2
    notempty
end
```

Comment (xsebek) [reply src/Swarm/Language/Pretty.hs:131]: @byorgey found it! I need to pass precedence to all but the last parameter.

Comment (xsebek) [reply src/Swarm/Language/Pretty.hs:133]: @byorgey I thought about function parameters too, but those might just be a bit complicated because of pattern matching operators. Let's leave that for a separate issue. 😅

**Comment by xsebek** [comment]
Technically we could also apply the same logic to sum and product types...

I will get back to this later and maybe refactor the pretty printing construct so that it works for more separators.

File: src/Swarm/Language/Pretty.hs (hunk 1 above)
Comment (byorgey) [reply src/Swarm/Language/Pretty.hs:133]: Oh, definitely leave it for a separate issue, I was just wondering out loud.

Comment (xsebek) [reply src/Swarm/Language/Pretty.hs:138]: I added it to the check list in #1571. 🙂

File: src/Swarm/Util.hs [hunk 2]
```diff
@@ -239,6 +240,23 @@ applyWhen False _ x = x
...
+--
+-- Example:
+--
+-- >>> unsnocNE (1 :| [2, 3])
+-- ([1,2],3)
+--
+-- >>> unsnocNE (1 :| [])
+-- ([],1)
+unsnocNE :: NonEmpty a -> ([a], a)
+unsnocNE (x :| xs) = go x xs
```
Comment (xsebek) [inline src/Swarm/Util.hs:255]: @kostmo I noticed there is a new HLint warning, but I could not find how to do this using our libraries.

I found this using Hoogle and borrowed the code.

File: test/unit/TestLanguagePipeline.hs [hunk 3]
```diff
@@ -417,3 +411,14 @@ testLanguagePipeline =
...
+-- | Check round tripping of term from and to text, then test ToJSON/FromJSON.
+roundTripTerm :: Text -> Assertion
+roundTripTerm txt = do
+  assertEqual "roundtrip (readTerm -> prettyText)" txt (prettyText term)
+  assertEqual "roundtrip (ToJSON -> FromJSON)" term (decodeThrow $ encode term)
+ where
+  decodeThrow v = case eitherDecode v of
+    Left e -> error $ "Decoding of " <> from (T.decodeUtf8 (from v)) <> " failed with: " <> from e
+    Right x -> x
+  term = fromMaybe (error "empty document") $ either (error . T.unpack) id $ readTerm txt
```
Comment (xsebek) [inline test/unit/TestLanguagePipeline.hs:424]: @byorgey I changed the function to produce better errors on round tripping and not elaborate.
```diff
- roundtrip
- expected: ProcessedTerm (Module {moduleAST = Syntax' {_sLoc = SrcLoc 0 30, _sTerm = SBind Nothing (Syntax' {_sLoc = SrcLoc 0 14, _sTerm = SDef False (LV {lvSrcLoc = SrcLoc 4 6, lvVar = "x"}) Nothing (Syntax' {_sLoc = SrcLoc 8 11, _sTerm = TInt 41, _sType = Forall [] (TyBaseF BInt)}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}) (Syntax' {_sLoc = SrcLoc 16 30, _sTerm = SDef False (LV {lvSrcLoc = SrcLoc 20 22, lvVar = "y"}) Nothing (Syntax' {_sLoc = SrcLoc 24 27, _sTerm = TInt 42, _sType = Forall [] (TyBaseF BInt)}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}, moduleCtx = Ctx {unCtx = fromList [("x",Forall [] (TyBaseF BInt)),("y",Forall [] (TyBaseF BInt))]}}) (Requirements {capReqs = fromList [CPower,CEnv], devReqs = fromList [], invReqs = fromList []}) (Ctx {unCtx = fromList [("x",Requirements {capReqs = fromList [], devReqs = fromList [], invReqs = fromList []}),("y",Requirements {capReqs = fromList [], devReqs = fromList [], invReqs = fromList []})]})
- but got: ProcessedTerm (Module {moduleAST = Syntax' {_sLoc = SrcLoc 0 32, _sTerm = SBind Nothing (Syntax' {_sLoc = SrcLoc 0 15, _sTerm = SDef False (LV {lvSrcLoc = SrcLoc 4 6, lvVar = "x"}) Nothing (Syntax' {_sLoc = SrcLoc 9 12, _sTerm = TInt 41, _sType = Forall [] (TyBaseF BInt)}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}) (Syntax' {_sLoc = SrcLoc 17 32, _sTerm = SDef False (LV {lvSrcLoc = SrcLoc 21 23, lvVar = "y"}) Nothing (Syntax' {_sLoc = SrcLoc 26 29, _sTerm = TInt 42, _sType = Forall [] (TyBaseF BInt)}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}), _sType = Forall [] (TyCmdF (TyBaseF BUnit))}, moduleCtx = Ctx {unCtx = fromList [("x",Forall [] (TyBaseF BInt)),("y",Forall [] (TyBaseF BInt))]}}) (Requirements {capReqs = fromList [CPower,CEnv], devReqs = fromList [], invReqs = fromList []}) (Ctx {unCtx = fromList [("x",Requirements {capReqs = fromList [], devReqs = fromList [], invReqs = fromList []}),("y",Requirements {capReqs = fromList [], devReqs = fromList [], invReqs = fromList []})]})
+ roundtrip (readTerm -> prettyText)
+ expected: "def x = 41 end; def y = 42 end"
+ but got: "def x = 41 end;\ndef y = 42 end"
```

AFAIK `readTerm` will not typecheck, is that OK or should I use another function?

Comment (xsebek) [reply test/unit/TestLanguagePipeline.hs:424]: I would like to eventually use this function for #1469, thought that might mean either a copy in integration tests or a common test utility library.

File: scripts/compare-format.sh [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+MIN=10
+MAX=200
+STEP=5
+
+function help() {
+    echo "$0 [--min $MIN --max $MAX --step $STEP] EXAMPLE_FILE.sw"
+    echo
+    echo "This script helps to compare the format layout for a range"
+    echo "of output widths. Afterwards it prints those that differ"
+    echo "as markdown with tripple backticks."
```
Comment (byorgey) [inline scripts/compare-format.sh:12]:
```suggestion
    echo "as markdown with triple backticks."
```

File: scripts/compare-format.sh [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+}
+
+# Simple argumet parsing from https://stackoverflow.com/a/14203146
```
Comment (byorgey) [inline scripts/compare-format.sh:15]:
```suggestion
# Simple argument parsing from https://stackoverflow.com/a/14203146
```

File: test/unit/TestLanguagePipeline.hs (hunk 3 above)
Comment (byorgey) [reply test/unit/TestLanguagePipeline.hs:424]: Yes, it makes sense to use `readTerm` here instead of `processTerm`.

**Review by byorgey — APPROVED** [review]
Looks good to me!
