### PR TITLE
Do not warn about hidden directories

### LINKED ISSUE #2320: Testing does not exist for 00-ORDER.txt
**Describe the bug**

When run without `--debug=testing`, a message about an unknown Testing shows up.

**To Reproduce**

Compare the following:

```
swarm
swarm --debug=testing
```

When you open Messages in the main menu.

**Expected behavior**

When the testing debug option is not selected, the order file should not complain about an unknown Testing directory.

**Screenshots**

Image

**Additional context**

The debug options split might have caused this warning message:
* #2094

### PR DESCRIPTION
**Pull request by xsebek**
* refactor `loadScenarioDir`
* do not warn about hidden directories not being present as they were deliberately not loaded
* closes #2320

### CODE REVIEW

File: src/swarm-engine/Swarm/Game/ScenarioInfo.hs [hunk 1]
```diff
@@ -164,70 +166,73 @@ orderFileName = "00-ORDER.txt"
 testingDirectory :: FilePath
 testingDirectory = "Testing"
 
-readOrderFile :: (Has (Lift IO) sig m) => FilePath -> m [String]
-readOrderFile orderFile =
-  filter (not . null) . lines <$> sendIO (readFile orderFile)
+readOrderFile :: FilePath -> IO (Maybe [String])
```
Comment (byorgey) [inline src/swarm-engine/Swarm/Game/ScenarioInfo.hs:169]: Why the change to a concrete `IO` type, instead of `Has (Lift IO)`?

Comment (xsebek) [reply src/swarm-engine/Swarm/Game/ScenarioInfo.hs:169]: It's a simple IO function, so using sendIO is only noise.

Comment (byorgey) [reply src/swarm-engine/Swarm/Game/ScenarioInfo.hs:169]: OK, fair enough.

**Comment by xsebek** [comment]
@byorgey just to check, did you want to look at this later or did you intend to approve it? 🙂

**Review by byorgey — APPROVED** [review]
Sorry, slipped my mind, thanks for the nudge!  In addition to fixing the warning this looks like a very nice refactoring.
