### PR TITLE
Only check for escaped skolem variables among those just generated

### LINKED ISSUE #2101: Strange type checking error "Skolem variable would escape its scope"
**Describe the bug**

Typechecking the following program gives a strange error:
```
Skolem variable s1 would escape its scope
```
because it uses a renamed type variable it is not immediately obvious what this is even about.

**To Reproduce**

```Haskell
def for_each_bit : Int -> Int -> (Int -> Int -> Cmd a) -> Cmd Unit
  = \i. \xs. \act.
  if (xs == 0) {} {
    let ht = (xs - 2 * (xs / 2), xs / 2) in
    act i (fst ht);
    for_each_bit (i + 1) (snd ht) act
  }
end
```

**Expected behavior**

The error should use the original type variable name `a` and a less formal language to explain the issue.

In this case there might not even be a reason for the error and it should typecheck.

**Screenshots**
It is interesting that only a part of the function body does not typecheck:
Screenshot 2024-08-09 at 5 49 28 PM

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #2101.

- Modifies `skolemize` to return the list of generated variable names along with the substituted type (and remove an unnecessary call to `error`!)
- Then in `noSkolems` only check for relevant, recently-generated skolem variables instead of for any skolem variables at all.

### CODE REVIEW

File: test/unit/TestLanguagePipeline.hs [hunk 1]
```diff
@@ -656,6 +656,15 @@ testLanguagePipeline =
...
         ]
+    , testGroup
+        "nested let/def/annot #2101"
+        [ testCase
+            "nested polymorphic def/let"
+            (valid "def id : a -> a = \\y. let x = 3 in y end")
+        , testCase
+            "nested polymorphic def/annot"
+            (valid "def id : a -> a * Int = \\y. (y, 3 : Int) end")
+        ]
```
Comment (byorgey) [inline test/unit/TestLanguagePipeline.hs:667]: These minimal test cases were failing before the fix.

**Review by xsebek — APPROVED** [review]
This looks reasonable to me. 👍 

I am glad that the test examples here will parse, those would surprise me even more than the example I have given.
