### PR TITLE
Validate hex colors in `FromJSON` instance

### LINKED ISSUE #2236: Unparseable custom attribute colors cause a crash
**Describe the bug**
In a scenario description, if the `fg` or `bg` color specification in a custom attribute cannot be parsed, swarm crashes.

**To Reproduce**

Try loading the following scenario `.yaml` file:

```
version: 1
name: Custom attribute - invalid color
description: |
  Invalid color in custom attribute
creative: false
attrs:
  - name: bogus
    bg: "this is not a color"
terrains:
  - name: whatzit
    attr: bogus
    description: |
      A thingy
robots:
  - name: base
    dir: east
world:
  dsl: |
    {grass}
  palette:
    'B': [grass, null, base]
    '.': [whatzit]
  upperleft: [0, 0]
  map: |
    B.
```

This results in:

```
$ ./scripts/play.sh -i Testing/_Validation/unparseable-attr-color.yaml
swarm: Data.Colour.SRGB.sRGB24read: no parse
CallStack (from HasCallStack):
  error, called at ./Data/Colour/SRGB.hs:128:3 in colour-2.3.6-01a45f2577c459ed9632a48ba99a66e313619b5bf990fc54e630e96fb26912b8:Data.Colour.SRGB
```

Note that the scenario successfully validates and loads; the error is thrown sometime later, perhaps when it is being rendered.

**Expected behavior**
The scenario should fail to validate with a reasonable error message.

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #2236.  Stores `Kolor` instead of `Text` inside a `HexColor`, and validates and parses it when reading from JSON.  This simplifies the code in multiple places where we were taking the `Text` out of a `HexColor` and parsing it.

### CODE REVIEW

File: src/swarm-scenario/Swarm/Game/Scenario/Style.hs [hunk 1]
```diff
@@ -38,17 +40,36 @@ instance FromJSON StyleFlag where
...
+  -- There is no Ord instance for Colour a, but we need one to use
+  -- with OccurrenceEncoder, so we make our own.
+  --
+  -- We use toRGB here since it does no conversions whatsoever, it
+  -- simply unpacks the raw color data into an RGB triple.  For the
+  -- purposes of an Ord instance, it doesn't matter: we just want a
+  -- consistent way to put a total ordering on colors as fast as
+  -- possible.
+  compare (HexColor (toRGB -> RGB r1 g1 b1)) (HexColor (toRGB -> RGB r2 g2 b2)) =
+    compare r1 r2 <> compare g1 g2 <> compare b1 b2
```
Comment (kostmo) [inline src/swarm-scenario/Swarm/Game/Scenario/Style.hs:58]: would it be simpler to use [3-tuples](https://hackage.haskell.org/package/ghc-prim-0.13.0/docs/GHC-Tuple.html#t:Ord)?
```
compare (r1, g1, b1) (r2, g2, b2)
```

File: src/swarm-scenario/Swarm/Game/Scenario/Style.hs [hunk 2]
```diff
@@ -38,17 +40,36 @@ instance FromJSON StyleFlag where
...
+
+instance ToJSON HexColor where
+  toJSON = toJSON . T.pack . sRGB24show . getHexColor
 
 instance ToPixel HexColor where
-  toPixel (HexColor colorText) = PixelRGBA8 r g b 255
+  toPixel (HexColor kolor) = PixelRGBA8 r g b 255
    where
-    temp :: Kolor
-    temp = sRGB24read $ T.unpack colorText
```
Comment (kostmo) [inline src/swarm-scenario/Swarm/Game/Scenario/Style.hs:50]: Maybe want to ban `sRGB24read` in `.hlint.yaml` since it is partial

**Review by kostmo — APPROVED** [review]
Nice improvement.

File: src/swarm-scenario/Swarm/Game/Scenario/Style.hs (hunk 2 above)
Comment (byorgey) [reply src/swarm-scenario/Swarm/Game/Scenario/Style.hs:50]: Good idea, done.
