### PR TITLE
Child robots only inherit their parent's `displayAttr`

### LINKED ISSUE #1693: Built robots all look like `Ω`
**Describe the bug**
Robots built by the `base` look like `Ω`.

**To Reproduce**
Start a classic game, and execute `build {move}`.  Observe that the new robot looks like `Ω`.

**Expected behavior**
The built robot should look like `^`.

**Screenshots**
build-omega

### PR DESCRIPTION
**Pull request by byorgey**
Fixes #1693.  It's not necessarily appropriate to copy the entire `Display` record.  So instead, we explicitly list the fields that should be inherited.  For now, it is only `displayAttr`, but we could add `invisible` in the future (see #1670, #1663).

Tested to make sure behavior is preserved with:
```
scripts/play.sh -i scenarios/Challenges/Ranching/beekeeping.yaml --autoplay
```

### CODE REVIEW

File: src/swarm-util/Swarm/Util/Lens.hs [hunk 1]
```diff
@@ -40,3 +43,7 @@ makeLensesExcluding exclude =
         & lensField . mapped . mapped %~ \fn n ->
           if n `elem` exclude then [] else fn n
     )
+
+-- | Copy a given field from one record to another.
+inherit :: Lens' s a -> s -> (s -> s)
```
Comment (kostmo) [inline src/swarm-util/Swarm/Util/Lens.hs:48]: Neat.

**Review by kostmo — APPROVED** [review]
